### ISSUE TITLE
NoDice crashes when opening or creating level

### ISSUE THREAD

**Issue by PyroLagus** [captainsouthbird/SMB3Utilties#1]
Whenever I try to open or make a new level, NoDice crashes with the error message 

> Attempt to unlock mutex that was not locked

I'm on ArchLinux, and here are relevant pkg-config outputs:

```
pkg-config gtk+-2.0 --cflags
-pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include

pkg-config gtk+-2.0 --libs
-lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype
```

The installed gtk2 is version 2.24.31-1 and glib2 is version 2.52.3-1

I made a gdb backtrace, which is here:

```
(gdb) bt
#0  0x00007ffff557c8c0 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff557df72 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff5e891dd in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5e89c9e in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#4  0x000055555555f980 in run_6502_timeout_thread ()
#5  0x00007ffff5e6bae5 in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff48d7049 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff5636f0f in clone () at /usr/lib/libc.so.6
```
I also had to remove the call to g_thread_init in gui.c to get it to compile in the first place, so it might have something to do with that. The diff is here:

```
diff --git a/src/NoDice/gui.c b/src/NoDice/gui.c
index bd99623..dc45892 100644
--- a/src/NoDice/gui.c
+++ b/src/NoDice/gui.c
@@ -2159,7 +2159,7 @@ static void gui_create_right_pane(GtkWidget *vbox)
 int gui_init()
 {
        // Initialize threading
-       g_thread_init(NULL);
+       //g_thread_init(NULL);
 
        // Create the main window
        gui_main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
```

When I compile without those changes, I get this error message:

```
gcc  obj/NoDice/gui_popups.o  obj/NoDice/gui.o  obj/NoDice/edit.o  obj/NoDice/gui_property_box.o  obj/NoDice/main.o  obj/NoDice/gui_overlay.o  obj/NoDice/gui_combobox_simple.o  obj/NoDice/ppu.o  obj/NoDice/gui_listbox.o -o ../../bin/NoDice obj/NoDiceLib/NoDiceLib.a -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype
obj/NoDice/gui.o: In function `gui_init':
gui.c:(.text+0x4791): undefined reference to `g_thread_init'
collect2: error: ld returned 1 exit status
make: *** [Makefile:60: ../../bin/NoDice] Error 1
```

presumably because g_thread_init has been deprecated since glib 2.32, but I'm not sure.

I don't think it should be hard to create a docker or flatpak for this, so you could probably just close this as WONTFIX. I just wanted to let you know.

**Comment by captainsouthbird** [comment]
I rewrote the 6502 emulator thread and replaced all the deprecated GLib calls. Give it a roll and let me know if that fixes it.

**Comment by PyroLagus** [comment]
Wow that was quick :D It works now, thanks.
